# Generated by Django 5.0.1 on 2024-05-30 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0002_remove_manager_games'),
        ('user', '0016_remove_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('status', models.SmallIntegerField(default=0)),
                ('type', models.SmallIntegerField(default=0)),
                ('screenshot', models.ImageField(upload_to='payment_screenshots/')),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('by_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.manager')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user.user')),
            ],
        ),
    ]
