# Generated by Django 5.0.1 on 2024-01-14 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousel',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='redeem',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
