# Generated by Django 5.0.1 on 2024-01-19 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_carousel_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
