# Generated by Django 5.0.1 on 2024-03-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_currency_paymentcard_working_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='working',
            name='comment',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
