# Generated by Django 5.0.1 on 2024-06-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_paymentcard_type_alter_paymentcard_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='working',
            name='is_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='working',
            name='is_technical',
            field=models.BooleanField(default=False),
        ),
    ]
