# Generated by Django 5.0.1 on 2024-06-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_working_is_partner_working_partner_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='working',
            name='partner_button',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
