# Generated by Django 5.0.1 on 2024-02-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_game_updated_at_alter_item_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='keyboard_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='game',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
