# Generated by Django 5.0.1 on 2024-02-11 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_game_is_archived_game_keyboard_type_game_visible_and_more'),
        ('user', '0003_payment_by_admin_payment_comment_alter_payment_user'),
    ]

    operations = [

    ]
