# Generated by Django 5.0.1 on 2024-02-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_order_by_admin_alter_order_game_alter_order_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='cash',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.CharField(default='0.00', max_length=20),
        ),
    ]
