# Generated by Django 5.0.1 on 2024-02-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_remove_order_order_order_cash_order_price'),
    ]

    operations = [

    ]
