# Generated by Django 5.0.1 on 2024-03-24 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='by_admin',
        ),
    ]
