# Generated by Django 4.2.11 on 2024-04-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('game', '0010_order_by_admin'),
    ]

    operations = [

    ]
