# Generated by Django 5.0.1 on 2024-06-02 16:01
import django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('game', '0011_order_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_archived',
        ),
        migrations.AddField(
            model_name='game',
            name='input_type',
            field=models.CharField(default='[]', max_length=500),
        ),
        migrations.AddField(
            model_name='item',
            name='benefit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),

    ]
