# Generated by Django 5.0.1 on 2024-06-09 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_remove_game_is_archived_remove_item_is_archived_and_more'),
        ('manager', '0005_remove_manager_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.manager'),
        ),
    ]
