# Generated by Django 5.0.1 on 2024-01-14 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=1000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('avatar', models.SmallIntegerField(default=0)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('notification_token', models.CharField(blank=True, max_length=1001, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('spam', models.IntegerField(default=0)),
                ('role', models.SmallIntegerField(default=0)),
                ('referal_code', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=55)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=55)),
                ('notification_token', models.CharField(blank=True, max_length=1001, null=True)),
                ('verify_code', models.CharField(max_length=6)),
                ('expired_date', models.SmallIntegerField(default=180)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('date', models.DateTimeField(auto_now=True)),
                ('status', models.SmallIntegerField(default=0)),
                ('screenshot', models.ImageField(upload_to='payment_screenshots/')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('warning', models.SmallIntegerField(blank=True, default=0)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
