# Generated by Django 5.0.1 on 2024-02-11 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_payment_date_remove_payment_warning_and_more'),
    ]

    operations = [

    ]
