# Generated by Django 5.0.1 on 2024-02-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_referal_code_user_invite_code_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='cashback',
            field=models.CharField(default='0.00', max_length=20),
        ),
    ]
