# Generated by Django 5.0.1 on 2024-03-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='type',
            field=models.SmallIntegerField(default=0),
        ),
    ]
