# Generated by Django 4.2.11 on 2024-03-23 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='by_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user'),
        ),
        migrations.CreateModel(
            name='CashbackOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_card', models.CharField(max_length=20)),
                ('amount', models.CharField(default='0.00', max_length=30)),
                ('status', models.SmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
