# Generated by Django 5.0.1 on 2024-03-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_payment_by_admin_cashbackorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='by_admin',
        ),
        migrations.AddField(
            model_name='cashbackorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cashbackorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='cashbackorder',
            name='payment_card',
            field=models.CharField(max_length=16),
        ),
    ]
