# Generated by Django 5.0.1 on 2024-03-24 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_remove_manager_games'),
        ('user', '0012_remove_payment_by_admin_cashbackorder_created_at_and_more'),
    ]

    operations = [

    ]
