# Generated by Django 4.2.11 on 2024-04-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_payment_by_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbackorder',
            name='amount',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=16),
        ),
    ]
