# Generated by Django 5.0.1 on 2024-05-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_cashbackorder_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='cashback',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
