# Generated by Django 5.0.1 on 2024-05-30 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_invite_cashback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
