# Generated by Django 5.0.1 on 2024-05-30 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0011_order_comment'),
        ('manager', '0002_remove_manager_games'),
        ('user', '0016_remove_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('cash', models.CharField(default='0', max_length=20)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('game_number', models.CharField(max_length=255)),
                ('status', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('by_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_by_admin', to='manager.manager')),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_by_user', to='user.user')),
            ],
        ),
    ]
