# Generated by Django 4.2.11 on 2024-03-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('game', '0008_alter_order_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('notification_token', models.CharField(blank=True, max_length=1001, null=True)),
                ('role', models.SmallIntegerField(default=0)),
                ('sign_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('games', models.ManyToManyField(blank=True, to='game.game')),
            ],
        ),
    ]
