# Generated by Django 5.0.1 on 2024-06-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_remove_game_is_archived_remove_item_is_archived_and_more'),
        ('manager', '0002_remove_manager_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='games',
            field=models.ManyToManyField(to='game.game'),
        ),
    ]
