# Generated by Django 5.0.1 on 2024-06-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_manager_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manager',
            name='is_superadmin',
            field=models.BooleanField(default=False),
        ),
    ]
