# Generated by Django 5.0.1 on 2024-06-09 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_manager_is_staff_manager_is_superadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='games',
        ),
    ]
